import {
  Cpu,
  Wheat,
  Factory,
  Shirt,
  Sofa,
  Coffee,
  Wifi,
  Wrench,
  Lightbulb,
  TrafficCone,
  Table,
  Droplet,
  type LucideIcon,
} from "lucide-react";
import type { Category, Product, Supplier } from "../types";

export const PRODUCTS: Product[] = [
  {
    id: "PRD-1042",
    name: "Industrial LED Panel Light",
    category: "Electronics",
    moq: "500 units",
    price: "$4.20",
    unit: "/unit",
    supplier: "Hangzhou BrightTech Co.",
    icon: "lightbulb",
    rating: 4.8,
  },
  {
    id: "PRD-1098",
    name: "Organic Basmati Rice (25kg)",
    category: "Agriculture",
    moq: "2 tons",
    price: "$610",
    unit: "/ton",
    supplier: "Indus Valley Grains Ltd.",
    icon: "wheat",
    rating: 4.9,
  },
  {
    id: "PRD-1156",
    name: "Galvanized Steel Pipe Set",
    category: "Construction",
    moq: "1,000 m",
    price: "$2.85",
    unit: "/meter",
    supplier: "IronCore Metal Works",
    icon: "roadBarrier",
    rating: 4.6,
  },
  {
    id: "PRD-1203",
    name: "Premium Cotton T-Shirt Blanks",
    category: "Fashion",
    moq: "300 pcs",
    price: "$1.95",
    unit: "/pc",
    supplier: "Daka Textile Mills",
    icon: "shirt",
    rating: 4.7,
  },
  {
    id: "PRD-1255",
    name: "Modular Office Desk Frame",
    category: "Furniture",
    moq: "50 units",
    price: "$38.00",
    unit: "/unit",
    supplier: "Nordic Frame Co.",
    icon: "table",
    rating: 4.5,
  },
  {
    id: "PRD-1309",
    name: "Cold-Pressed Olive Oil (1L)",
    category: "Food & Beverage",
    moq: "1,200 bottles",
    price: "$3.40",
    unit: "/bottle",
    supplier: "Aegean Harvest Exports",
    icon: "droplet",
    rating: 4.9,
  },
  {
    id: "PRD-1364",
    name: "Smart Home Hub Controller",
    category: "Electronics",
    moq: "200 units",
    price: "$12.50",
    unit: "/unit",
    supplier: "Shenzhen NextWave Tech",
    icon: "wifi",
    rating: 4.4,
    isNew: true,
  },
  {
    id: "PRD-1417",
    name: "PVC Pipe Fittings Bulk Pack",
    category: "Construction",
    moq: "5,000 pcs",
    price: "$0.32",
    unit: "/pc",
    supplier: "BuildRight Polymers",
    icon: "wrench",
    rating: 4.6,
    isNew: true,
  },
];

export const CATEGORIES: Category[] = [
  { id: "electronics", name: "Electronics", icon: "cpu", count: 1840 },
  { id: "agriculture", name: "Agriculture", icon: "wheat", count: 960 },
  { id: "construction", name: "Construction", icon: "hardHat", count: 1320 },
  { id: "fashion", name: "Fashion", icon: "shirt", count: 2105 },
  { id: "furniture", name: "Furniture", icon: "sofa", count: 740 },
  { id: "food", name: "Food & Beverage", icon: "coffee", count: 1080 },
];

export const ICON_MAP: Record<string, LucideIcon> = {
  cpu: Cpu,
  wheat: Wheat,
  industry: Factory,
  shirt: Shirt,
  sofa: Sofa,
  coffee: Coffee,
  wifi: Wifi,
  wrench: Wrench,
  lightbulb: Lightbulb,
  roadBarrier: TrafficCone,
  table: Table,
  droplet: Droplet,
};

export const SUPPLIERS: Supplier[] = [
  {
    id: "SUP-0118",
    name: "Hangzhou BrightTech Co.",
    industry: "Electronics Manufacturing",
    location: "Hangzhou, CN",
    rating: 4.8,
    reviews: 312,
    verified: true,
    icon: "cpu",
  },
  {
    id: "SUP-0224",
    name: "Indus Valley Grains Ltd.",
    industry: "Agricultural Exports",
    location: "Lahore, PK",
    rating: 4.9,
    reviews: 198,
    verified: true,
    icon: "wheat",
  },
  {
    id: "SUP-0337",
    name: "IronCore Metal Works",
    industry: "Steel & Metal Goods",
    location: "Gaziantep, TR",
    rating: 4.6,
    reviews: 154,
    verified: true,
    icon: "industry",
  },
  {
    id: "SUP-0451",
    name: "Daka Textile Mills",
    industry: "Apparel & Textiles",
    location: "Dhaka, BD",
    rating: 4.7,
    reviews: 267,
    verified: true,
    icon: "shirt",
  },
  {
    id: "SUP-0509",
    name: "Nordic Frame Co.",
    industry: "Furniture & Fixtures",
    location: "Gothenburg, SE",
    rating: 4.5,
    reviews: 89,
    verified: false,
    icon: "sofa",
  },
  {
    id: "SUP-0612",
    name: "Aegean Harvest Exports",
    industry: "Food & Beverage",
    location: "Izmir, TR",
    rating: 4.9,
    reviews: 221,
    verified: true,
    icon: "coffee",
  },
  {
    id: "SUP-0721",
    name: "Shenzhen NextWave Tech",
    industry: "Consumer Electronics",
    location: "Shenzhen, CN",
    rating: 4.4,
    reviews: 63,
    verified: true,
    icon: "wifi",
  },
  {
    id: "SUP-0834",
    name: "BuildRight Polymers",
    industry: "Construction Materials",
    location: "Karachi, PK",
    rating: 4.6,
    reviews: 182,
    verified: true,
    icon: "wrench",
  },
];
